	if(Lang=="russ") RbRussian->Checked=true;
	else RbEnglish->Checked=true;
	TR_(MainForm,"FOnline конфигуратор   v2.5.2","FOnline configurator   v2.5.2");
	TR_(BtnExecute,"Играть","Play");
	TR_(BtnParse,"Сохранить","Save");
	TR_(BtnExit,"Выход","Exit");
	TR_(TabOther,"Разное","Other");
	TR_(GbLanguage,"Язык \\ Language","Language \\ Язык");
	TR_(RbRussian,"Русский","Русский");
	TR_(RbEnglish,"English","English");
	TR_(GbOther,"","");
	TR_(CbWinNotify,"Извещение о сообщениях\nпри неактивном окне.","Flush window on\nnot active game.");
	TR_(CbSoundNotify,"Звуковое извещение о сообщениях\nпри неактивном окне.","Beep sound on\nnot active game.");
	TR_(CbInvertMessBox,"Инвертирование текста\nв окне сообщений.","Invert text\nin messbox.");
	TR_(CbLogging,"Ведение лога в 'FOnline.log'.","Logging in 'FOnline.log'.");
	TR_(CbLoggingTime,"Запись в лог с указанием времени.","Logging with time.");
	TR_(LabelFixedFPS,"Фиксированный\n         FPS","              Fixed\n               FPS");
	TR_(TabGame,"Игра","Game");
	TR_(GbGame,"Игра","Game");
	TR_(LabelScrollDelay,"Задержка скроллинга","Scroll delay");
	TR_(LabelScrollStep,"Шаг скроллинга","Scroll step");
	TR_(LabelTextDelay,"Время задержки текста (мс)","Text delay (ms)");
	TR_(CbAlwaysRun,"Постоянный бег","Always run");
	TR_(TabNet,"Сеть","Net");
	TR_(GbServer,"Игровой сервер","Game server");
	TR_(LabelServerHost,"Хост","Host");
	TR_(LabelServerPort,"Порт","Port");
	TR_(GbProxy,"Прокси","Proxy");
	TR_(LabelProxyType,"Тип","Type");
	TR_(RbProxyNone,"Нет","None");
	TR_(RbProxySocks4,"Socks4","Socks4");
	TR_(RbProxySocks5,"Socks5","Socks5");
	TR_(RbProxyHttp,"Http","Http");
	TR_(LabelProxyHost,"Хост","Host");
	TR_(LabelProxyPort,"Порт","Port");
	TR_(LabelProxyName,"Логин","Login");
	TR_(LabelProxyPass,"Пароль","Password");
	TR_(TabVideo,"Видео","Video");
	TR_(GbScreenSize,"Разрешение","Resolution");
	TR_(GbVideoOther,"","");
	TR_(LabelLight,"Яркость","Light");
	TR_(LabelSprites,"Кешируемые\nспрайты","Cache sprites");
	TR_(LabelTexture,"Размер текстур","Texture size");
	TR_(LabelMultisampling,"Мультисэмплинг 3d","Multisampling 3d");
	TR_(CbFullScreen,"Полноэкранный режим","Fullscreen");
	TR_(CbVSync,"Вертикальная синхронизация","VSync");
	TR_(CbAlwaysOnTop,"Поверх всех окон","Always on top");
	TR_(LabelAnimation3dFPS,"3d FPS","3d FPS");
	TR_(LabelAnimation3dSmoothTime,"Сглаживание 3d переходов","3d smooth transition");
	TR_(TabSound,"Звук","Sound");
	TR_(GbSoundVolume,"Громкость","Volume");
	TR_(LabelMusicVolume,"Музыка","Music");
	TR_(LabelSoundVolume,"Звуки","Sound");
	TR_(TabCombat,"Боевка","Combat");
	TR_(GbDefCmbtMode,"Режим боя по-умолчанию","Default combat mode");
	TR_(RbDefCmbtModeBoth,"Оба режима","Both modes");
	TR_(RbDefCmbtModeRt,"Реальное время","Real-time");
	TR_(RbDefCmbtModeTb,"Пошаговый режим","Turn-based");
	TR_(GbIndicator,"Индикатор патронов и износа","Ammo amount and deterioration display");
	TR_(RbIndicatorLines,"Линии","Lines");
	TR_(RbIndicatorNumbers,"Номера","Numbers");
	TR_(RbIndicatorBoth,"Линии и номера","Lines and numbers");
	TR_(GbCmbtMess,"Боевые сообщения","Combat messages");
	TR_(RbCmbtMessVerbose,"Полные","Verbose");
	TR_(RbCmbtMessBrief,"Краткие","Brief");
	TR_(GbDamageHitDelay,"Режим индикации повреждений над головой","Damage indication on head");
	TR_(LabelDamageHitDelay,"Задержка, в мс","Delay (ms)");
